apiVersion: v1
kind: Service
metadata:
  name: {{ include "ellingson-mineral.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ellingson-mineral.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ellingson-mineral.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
